version: "3.9"

services:
  mongo:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENERS=yes
    depends_on:
      - zookeeper
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"

  cart-service: 
    build: cart-service
    environment:
      DATABASE_URI: "mongodb+srv://denipanji:KOKIOonGVDN4jXNI@agreeculture.wupdwyx.mongodb.net/cart-service"
    depends_on:
      - mongo
      - nginx
    ports:
      - "9010:9010"
    restart: always

  offer-service:
    build: offer-service
    environment:
      DATABASE_URI: "mongodb+srv://denipanji:KOKIOonGVDN4jXNI@agreeculture.wupdwyx.mongodb.net/offer-service"
    depends_on:
      - mongo
      - nginx
    ports:
      - "9015:9015"
    restart: always

  transaction-service:
    build: transaction-service
    environment:
      DATABASE_URI: "mongodb+srv://denipanji:KOKIOonGVDN4jXNI@agreeculture.wupdwyx.mongodb.net/transaction-service"
    depends_on:
      - mongo
      - nginx
    ports: 
      - "9005:9005"
    restart: always

  user-service: 
    build: user-service
    environment: 
      DATABASE_URI: "mongodb+srv://denipanji:KOKIOonGVDN4jXNI@agreeculture.wupdwyx.mongodb.net/user-service"
    depends_on:
      - mongo
      - nginx
    ports: 
      - "9000:9000"
    restart: always
  
  wishlist-service: 
    build: wishlist-service
    environment:
      DATABASE_URI: "mongodb+srv://denipanji:KOKIOonGVDN4jXNI@agreeculture.wupdwyx.mongodb.net/wishlist-service"
    depends_on:
      - mongo
      - nginx
    ports:
      - "9025:9025"
    restart: always
  
  product-service:
    build: product-service
    environment:
      DATABASE_URI: "mongodb+srv://denipanji:KOKIOonGVDN4jXNI@agreeculture.wupdwyx.mongodb.net/product-service"
    depends_on:
      - mongo
      - nginx
    ports:
      - "9020"
    restart: always